version: '3.8'

services:
  hcc-pipeline:
    image: hcc-pipeline
    build: .
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}